"""Add team transfer requests

Revision ID: 8c394a4ed626
Revises: 010
Create Date: 2026-03-22 22:26:49.158807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c394a4ed626'
down_revision: Union[str, None] = '010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_transfer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('target_team_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_transfer_requests_company_id'), 'team_transfer_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_team_transfer_requests_current_team_id'), 'team_transfer_requests', ['current_team_id'], unique=False)
    op.create_index(op.f('ix_team_transfer_requests_id'), 'team_transfer_requests', ['id'], unique=False)
    op.create_index(op.f('ix_team_transfer_requests_requested_by_id'), 'team_transfer_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_team_transfer_requests_status'), 'team_transfer_requests', ['status'], unique=False)
    op.create_index(op.f('ix_team_transfer_requests_target_team_id'), 'team_transfer_requests', ['target_team_id'], unique=False)
    op.create_index(op.f('ix_team_transfer_requests_user_id'), 'team_transfer_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_transfer_requests_user_id'), table_name='team_transfer_requests')
    op.drop_index(op.f('ix_team_transfer_requests_target_team_id'), table_name='team_transfer_requests')
    op.drop_index(op.f('ix_team_transfer_requests_status'), table_name='team_transfer_requests')
    op.drop_index(op.f('ix_team_transfer_requests_requested_by_id'), table_name='team_transfer_requests')
    op.drop_index(op.f('ix_team_transfer_requests_id'), table_name='team_transfer_requests')
    op.drop_index(op.f('ix_team_transfer_requests_current_team_id'), table_name='team_transfer_requests')
    op.drop_index(op.f('ix_team_transfer_requests_company_id'), table_name='team_transfer_requests')
    op.drop_table('team_transfer_requests')
    # ### end Alembic commands ###
