"""Add company_code

Revision ID: d39eb985c017
Revises: 8c394a4ed626
Create Date: 2026-03-23 11:04:47.966812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39eb985c017'
down_revision: Union[str, None] = '8c394a4ed626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_code', sa.String(length=3), nullable=True))
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_column('companies', 'company_code')
    # ### end Alembic commands ###
