class RouteNames {
  RouteNames._();

  static const String login = 'login';
  static const String dashboard = 'dashboard';
  static const String team = 'team';
  static const String teamMember = 'teamMember';
  static const String leads = 'leads';
  static const String leadDetail = 'leadDetail';
  static const String clients = 'clients';
  static const String clientDetail = 'clientDetail';
  static const String tasks = 'tasks';
  static const String followUps = 'followUps';
  static const String orders = 'orders';
  static const String managerOrders = 'managerOrders';
  static const String invoiceDetail = 'invoiceDetail';
  static const String notifications = 'notifications';
  static const String stock = 'stock';
  static const String invoices = 'invoices';
  static const String aiAssistant = 'aiAssistant';
  static const String settings = 'settings';
  static const String profile = 'profile';
  static const String performance = 'performance';
  static const String managerReports = 'managerReports';
  static const String more = 'more';
  static const String revenue = 'revenue';
  static const String mdTeams = 'mdTeams';
  static const String employeeLookup = 'employeeLookup';
  static const String employeeDetail = 'employeeDetail';
  static const String mdInvoices = 'mdInvoices';
  static const String adminUsers = 'adminUsers';
  static const String adminUserDetail = 'adminUserDetail';
  static const String adminTeamsRoute = 'adminTeamsRoute';
  static const String adminTeamDetail = 'adminTeamDetail';
  static const String adminApprovalsRoute = 'adminApprovalsRoute';
  static const String purchaseSales = 'purchaseSales';
  static const String purchaseSaleDetail = 'purchaseSaleDetail';
  static const String purchaseInvoices = 'purchaseInvoices';
  static const String purchaseInvoiceDetail = 'purchaseInvoiceDetail';
  static const String purchaseMonitoring = 'purchaseMonitoring';
  static const String platformCompanies = 'platformCompanies';
  static const String platformCompanyDetail = 'platformCompanyDetail';
  static const String platformPending = 'platformPending';
  static const String platformLogs = 'platformLogs';
  static const String platformPlans = 'platformPlans';
  static const String platformSession = 'platformSession';
}
